name: "yolo26seg_gpu_pre_gpu_post"
platform: "ensemble"
max_batch_size: 1
input [{ name: "IMAGE" data_type: TYPE_UINT8 dims: [-1] }]
output [
  { name: "NUM_DETECTIONS" data_type: TYPE_INT32 dims: [1] },
  { name: "BOXES" data_type: TYPE_INT32 dims: [100, 4] },
  { name: "SCORES" data_type: TYPE_FP32 dims: [100] },
  { name: "CLASSES" data_type: TYPE_INT32 dims: [100] },
  { name: "MASK_OFFSETS" data_type: TYPE_INT64 dims: [101] },
  { name: "MASK_SHAPES" data_type: TYPE_INT32 dims: [100, 2] },
  { name: "MASK_DATA" data_type: TYPE_UINT8 dims: [-1] }
]
ensemble_scheduling {
  step [
    {
      model_name: "yolo26seg_dali_preprocess" model_version: -1
      input_map { key: "IMAGE" value: "IMAGE" }
      output_map { key: "PREPROCESSED" value: "model_input" }
      output_map { key: "ORIGINAL_SIZE" value: "original_size" }
    },
    {
      model_name: "yolo26seg_trt" model_version: -1
      input_map { key: "images" value: "model_input" }
      output_map { key: "output0" value: "detections" }
      output_map { key: "output1" value: "prototypes" }
    },
    {
      model_name: "yolo26seg_dali_postprocess" model_version: -1
      input_map { key: "DETECTIONS" value: "detections" }
      input_map { key: "PROTOTYPES" value: "prototypes" }
      input_map { key: "ORIGINAL_SIZE" value: "original_size" }
      output_map { key: "NUM_DETECTIONS" value: "NUM_DETECTIONS" }
      output_map { key: "BOXES" value: "BOXES" }
      output_map { key: "SCORES" value: "SCORES" }
      output_map { key: "CLASSES" value: "CLASSES" }
      output_map { key: "MASK_OFFSETS" value: "MASK_OFFSETS" }
      output_map { key: "MASK_SHAPES" value: "MASK_SHAPES" }
      output_map { key: "MASK_DATA" value: "MASK_DATA" }
    }
  ]
}
