name: "yolo26seg_trt"
platform: "tensorrt_plan"
max_batch_size: 1
input [{ name: "images" data_type: TYPE_FP32 format: FORMAT_NCHW dims: [3, 640, 640] }]
output [
  { name: "output0" data_type: TYPE_FP32 dims: [300, 38] },
  { name: "output1" data_type: TYPE_FP32 dims: [32, 160, 160] }
]
instance_group [{ kind: KIND_GPU count: 1 }]
